import { Inter } from "next/font/google";
import Filters from "./components/Filters";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto p-4">
          <Filters /> {/* Include Filters here */}
          <main>{children}</main> {/* Page content will be rendered here */}
        </div>
      </body>
    </html>
  );
}
